---
body:
  - type: markdown
    attributes:
        value: |
            Thanks for wanting to improve zshclock! Choose a descriptive title and fill out this form to submit your feature request!
  - type: textarea
    id: suggestion
    attributes:
        label: "Suggestion"
        description: "What would you like to see zshclock add, change, remove, or improve?"
        placeholder: |
            Add bees. Add lots of bees. The clock doesn't have enough bees, and lemme tell you, I goddamn LOVE bees.
    validations:
        required: true
  - type: textarea
    id: reason
    attributes:
        label: "Reason"
        description: "Why should zshclock consider this suggestion?"
        placeholder: |
            Bees are, like, really good for the environment? If zshclock had bees, it would definitely be more awesome. Plus, the clock could finally pollinate itself.
    validations:
        required: true
  - type: textarea
    id: extras
    attributes:
        label: "Extras"
        description: "Is there anything else you'd like to add? Context, history, images, code examples, etc."
        placeholder: |
            I'm not really particular on what kind of bee zshclock adds. There's, like, a jabillion different kinds, and any of them would do, so long as there's lots and lots. Please. And thank you.
    validations:
        required: false
  - type: checkboxes
    id: acknowledgement
    attributes:
        label: "Acknowledgement"
        description: "This form is only a request, and in no way guarantees this feature will be added."
        options:
          - label: "I understand"
            required: true
          - label: "I will abide by the [Code of Bill and Ted](https://github.com/tenault/zshclock/blob/main/.github/CODE_OF_CONDUCT.md)"
            required: true
...
